### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by BBoldt** [MinecraftModArchive/Dendrology#21]
Sorry, I don't know if this mod was ready to be used yet, I just wanted to try it out and see what it was all about.

Here is the server crashlog:
http://pastebin.com/v0yQVQYD

Using:
Ancient Trees 1.1.0
Koresample 1.0.0
Forge 1277

**Comment by ScottKillen** [comment]
Go to http:github.com/MinecraftModArchive/Dendrology/releases/latest and grab the copy of KoreSample linked there. I think the copy you got is corrupt. I will fix that. 

Please let me know if that works. Thank you and sorry for the inconvenience.

**Comment by ScottKillen** [comment]
OK @BBoldt Thank you for reporting this.

I have replaced all downloads with the correct binaries.

Here is a link: https://github.com/MinecraftModArchive/KoreSample/releases/download/v1.0.0/KoreSample-1.7.10-1.0.0.jar
