### ISSUE TITLE
Latest Download - Typo

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModArchive/Dendrology#23]
Current download link is

https://github.com/MinecraftModArchive/Dendrology/releases/download/v1.2.1/AncientTrees-1.7.10-1.2.2.jar

which results in a 404 error. The working link is

https://github.com/MinecraftModArchive/Dendrology/releases/download/v1.2.2/AncientTrees-1.7.10-1.2.2.jar

The release is still available from the releases tab.

**Comment by ScottKillen** [comment]
@Shadows-of-Fire Thank you!
