### ISSUE TITLE
Chisel blocks need localization

### ISSUE THREAD

**Issue by SnowShock35** [MinecraftModArchive/Dendrology#26]
Hi Scott,

Quick bug to report, here are the details...

* Minecraft version: 1.7.10
* Forge version: 1291
* Ancient trees version: 1.2.3
* KoreSample version: 1.2.5

**Description**
Chisel blocks added in this version of ancient trees need localization as they all are missing it.

https://imgur.com/a/NNABu

**Comment by ScottKillen** [comment]
@SnowShock35 Which locale are you using?

**Comment by ScottKillen** [comment]
@SnowShock35 Nevermind. I see the problem.

**Comment by ScottKillen** [comment]
Added images from imgur to preserve them.

![4qjxdad](https://cloud.githubusercontent.com/assets/1509989/6215023/f32fd154-b5ca-11e4-8671-333ed46fff8b.png)
![90zfapu](https://cloud.githubusercontent.com/assets/1509989/6215025/f3316c4e-b5ca-11e4-8a75-673c358421b7.png)
![h2cykg4](https://cloud.githubusercontent.com/assets/1509989/6215027/f332375a-b5ca-11e4-9754-7f3a247bc2ef.png)
![letz3nx](https://cloud.githubusercontent.com/assets/1509989/6215028/f332ddd6-b5ca-11e4-9042-7908a3cf11fe.png)
![ulzlzcj](https://cloud.githubusercontent.com/assets/1509989/6215026/f3323a48-b5ca-11e4-96ea-53eb1541e497.png)
![w0ckjfd](https://cloud.githubusercontent.com/assets/1509989/6215024/f3301470-b5ca-11e4-8a3c-8ca4634359ad.png)
