### ISSUE TITLE
Sapling subblock chest loot not generating

### ISSUE THREAD

**Issue by QuantumZari** [MinecraftModArchive/Dendrology#29]
Subblocks for the saplings are not being registered in the chest loot tables. This causes only Acemus and Lata saplings to generate in chests.

**Comment by ate0ate** [comment]
Oh man, that's why I can never find more than those two trees! I wondered what was going on. I tried adjusting the configs to no avail. Kinda hard to use this mod without retrogen then. Hope this one gets fixed.

**Comment by ScottKillen** [comment]
A solution is coming soon. Real life intervenes for the moment.

**Comment by ate0ate** [comment]
Thanks for the fix:)
