### ISSUE TITLE
Crash at startup using new chisel 2 builds...

### ISSUE THREAD

**Issue by ate0ate** [MinecraftModArchive/Dendrology#31]
It seems chisel is making some API changes and using some of the newer builds now results in this crash at startup. Just a heads-up. Thanks!

http://pastebin.com/cj6f38vP

**Comment by tterrag1098** [comment]
Tip, everything you are doing now can be done through the *actual* API in the newer builds. This should be released soon.

This means you can get rid of those stub classes you are currently using...

**Comment by ScottKillen** [comment]
Thanks to both of you. I have been anxiously awaiting the new API!

**Comment by tterrag1098** [comment]
Good to know, let me know (I'm in IRC as well, #Chisel works) if you have any issues with it, it is still somewhat WIP.

**Comment by ScottKillen** [comment]
@tterrag1098 API seems to work beautifully. I have only one issue so far. See TheCricket/Chisel-2#314

I still have testing ahead, but this makes things a lot smoother.

**Comment by ewsmith** [comment]
more new chisel release crashes! \o/
http://pastebin.com/afkKxZBQ

**Comment by ate0ate** [comment]
Looks like chisel2 v2.4.0 is coming out of beta so can we look forward to your wonderful api implementation being released?

**Comment by ScottKillen** [comment]
Thanks for the heads up. I checked last night but must have just missed the release. 

Yes. My update has been waiting in the can. I need to update the api, me the everything and then test. I expect to have something within 24 hours.

**Comment by ScottKillen** [comment]
Fixed in 18701801ad91941430d1f8fac232463d08c73b30

Released in [1.6.0](https://github.com/MinecraftModArchive/Dendrology/releases/tag/v1.6.0).
