### ISSUE TITLE
Chisel 2.4.0 Ancient Trees 1.6.0, forge 1.7.10-10.13.4.1472 crash on load.

### ISSUE THREAD

**Issue by Oxosorrel** [MinecraftModArchive/Dendrology#36]
Using
AncientTrees-1.7.10-1.6.0
Chisel2-2.4.0.38

Forge:
forge-1.7.10-10.13.4.1472-1.7.10-universal
(fastcraft 1.22 test10 installed)

All work fine in single player.

However SMP server crashes on load:
Crashlog:
https://gist.github.com/Oxosorrel/1874f7da101b819f2c36

Shall I strip the server down to just these mods and try again? (Its got a obscene large custom list of mods on the server)... or is this crash log helpful?

**Comment by ScottKillen** [comment]
Would you mind posting the log again... This link is bad.

**Comment by Oxosorrel** [comment]
Pastbin cuz I fail at gist

http://pastebin.com/V6gruzzy

**Comment by ScottKillen** [comment]
Fixed in 1.6.1

**Comment by Oxosorrel** [comment]
Woo, thanks for the quick turn around.
