### ISSUE TITLE
Crash with new Chisel

### ISSUE THREAD

**Issue by ruyanve** [MinecraftModArchive/Dendrology#39]
Chisel is under a new regime and the new version doesn't get recognized by AT. Or it doesn't meet it's requirements. 1.4 something

Using:
Forge 1492
Kore Sample 1.3.2
AT 1.6.2
Chisel-CT2.5.0.1

https://github.com/Chisel-Team/Chisel

**Comment by ScottKillen** [comment]
Please post a link to you forge log with details of the problem.

Also...as this mod uses the API published by Chisel, you might first start by posting an issue on the chisel repo letting them know that they have broken its API...

**Comment by ruyanve** [comment]
Hm I'm sorry, I jumped to the conclusion that it was on AT side only, because other mods in my collection don't complain about it i.e. the client starts fine without AT... and I figured in that many mods must be another mod besides AT that uses Chisel API.

And there's nothing special in the log besides this:
http://pastebin.com/0p7yqW65

Well, I'll poke the chisel guys with it I guess :-)

**Comment by ScottKillen** [comment]
No problem...

The logs show that the chisel mod has changed its versioning scheme... The have started appending CT to the front of their version number...

AT says that it needs version 2.4.0.38 or later...and FML doesn't know where version CT2.5.0.1 fits in the scheme of things.

**Comment by ScottKillen** [comment]
Waiting for response over at https://github.com/Chisel-Team/Chisel/issues/1

**Comment by ruyanve** [comment]
Fixed in latest version.

Thank again for your help!!

**Comment by ScottKillen** [comment]
My pleasure!
