### ISSUE TITLE
Update for Minecraft 1.10?

### ISSUE THREAD

**Issue by DraconianBeryl** [MinecraftModArchive/Dendrology#42]
Hi Scott,

Are you currently planning on updating the mod for Minecraft 1.10?

I've just forked both Dendrology and KoreSample and plan on starting that work.  If you've already started I will either abandon my effort or am willing to provide assistance, your preference.

If I haven't heard from you by the time I've finished my work, I'll send you pull requests for the updating work and then release them under different names, referring back to you and your work as the basis.

Thanks,
Draconian Beryl

**Comment by ScottKillen** [comment]
Draconian Beryl,

I will not be updating either mod. Feel free to do as you please. I am flattered that you want to continue the work.

You may change the name if you'd like or use the names as is. If I can do anything to help smooth your progress, please let me know.

Thanks!

Scott

**Comment by DraconianBeryl** [comment]
As an update, I seriously over-estimated how much time I would have available to work on this.  I'm officially abandoning my efforts.

Sorry.  :(

**Comment by ScottKillen** [comment]
No worries. I completely understand.
