### ISSUE TITLE
Trees do not generate in other world types (ATG)

### ISSUE THREAD

**Issue by WolfieWaffle** [MinecraftModArchive/Dendrology#43]
I set the tree value very high and tested on a normal world, on a normal world they spawn but do not in an ATG world (and I would assume based on this, any other non-default world type)

**Comment by ScottKillen** [comment]
Please be more specific. I do not know what you mean by "tree value". 

Nothing in the code differentiates between world types. Any world type that fires Forge terrain generation events gets trees. 

I use ATG exclusively and it works for me.
