### ISSUE TITLE
Log generation does not replace snow

### ISSUE THREAD

**Issue by WolfieWaffle** [MinecraftModArchive/Dendrology#44]
![2017-03-26_22 55 54](https://cloud.githubusercontent.com/assets/8770485/24341574/d26102d4-1277-11e7-94c5-9fa7ff51c7f3.png)
Attached is a picture of natural generation that I found, where snow is overriding the log.
(Might be ATG, if the problem does not reside here I will post there)

**Comment by ScottKillen** [comment]
This works fine for me... and you just posted an issue that trees didn't gen in ATG.
